package com.xstd.ip.dao;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig silenceAppDaoConfig;

    private final SilenceAppDao silenceAppDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
        super(db);

        silenceAppDaoConfig = daoConfigMap.get(SilenceAppDao.class).clone();
        silenceAppDaoConfig.initIdentityScope(type);

        silenceAppDao = new SilenceAppDao(silenceAppDaoConfig, this);

        registerDao(SilenceApp.class, silenceAppDao);
    }

    public void clear() {
        silenceAppDaoConfig.getIdentityScope().clear();
    }

    public SilenceAppDao getSilenceAppDao() {
        return silenceAppDao;
    }

}
